name: procura_online
description: Procura Online App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.24.0
  share: ^0.6.5+4
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^1.0.2+2
  modal_progress_hud: ^0.1.3
  file_picker: ^2.1.5+1
  smart_select: ^4.3.2
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  http_parser: ^3.1.4
  flutter_html: ^1.2.0
  flutter_svg: ^0.19.0
  flutter_speed_dial: ^1.2.5
  google_fonts: ^1.1.1
  shimmer: ^1.1.2
  uuid: ^2.2.2
  intl: ^0.16.1
  onesignal_flutter: ^2.6.2
  flutter_local_notifications: ^3.0.3
  introduction_screen: ^1.0.9
  badges: ^1.1.6
  list_tile_more_customizable: ^1.3.3
  cached_network_image: ^2.5.0
  octo_image: ^0.3.0
  photo_view: ^0.10.3
  carousel_pro: ^1.0.0
  percent_indicator: ^2.1.9
  awesome_dialog: ^1.3.1
  json_annotation: ^3.1.1
  pusher_client: ^1.1.3
  animations: ^1.1.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  focus_detector: ^1.1.0+1
  flutter_datetime_picker: ^1.5.0
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.1
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/