name: procura_online
description: Procura Online App
version: 2.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.26.0
  share: ^2.0.1
  modal_progress_hud: ^0.1.3
  file_picker: ^2.1.5+1
  smart_select: ^4.3.2
  dio: ^4.0.0-prev2
  dio_cache_interceptor: ^2.0.0-rc.1
  http_parser: ^4.0.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_speed_dial: ^3.0.5
  google_fonts: ^2.0.0
  shimmer: ^1.1.2
  uuid: ^3.0.1
  intl: ^0.17.0
  onesignal_flutter: ^2.6.3
  flutter_local_notifications: ^4.0.1+2
  introduction_screen: ^2.0.0
  badges: ^2.0.0-nullsafety.1
  list_tile_more_customizable: ^1.3.3
  cached_network_image: ^2.5.1
  octo_image: ^0.3.0
  photo_view: ^0.11.1
  carousel_pro: ^1.0.0
  percent_indicator: ^2.1.9+1
  awesome_dialog: ^1.3.2
  json_annotation: ^4.0.0
  pusher_client: ^1.1.3
  animations: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  focus_detector: ^2.0.0
  flutter_datetime_picker: ^1.5.0
  flutter_swiper: ^1.1.6
  url_launcher: ^5.7.10
  maps_launcher: ^1.2.2+2
  package_info: ^2.0.0
  device_info: ^2.0.0
  diacritic: ^0.1.3
  sizer: ^1.1.8
  sqlite3_flutter_libs: ^0.4.1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/